/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                '#faf8ff',
        'surface-dim':            '#d2d9f4',
        'surface-bright':         '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':  '#f2f3ff',
        'surface-container':      '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface':             '#131b2e',
        'on-surface-variant':     '#444653',
        'inverse-surface':        '#283044',
        'inverse-on-surface':     '#eef0ff',
        'outline':                '#757684',
        'outline-variant':        '#c4c5d5',
        'surface-tint':           '#3755c3',
        'primary':                '#00288e',
        'on-primary':             '#ffffff',
        'primary-container':      '#1e40af',
        'on-primary-container':   '#a8b8ff',
        'inverse-primary':        '#b8c4ff',
        'primary-fixed':          '#dde1ff',
        'primary-fixed-dim':      '#b8c4ff',
        'on-primary-fixed':       '#001453',
        'on-primary-fixed-variant': '#173bab',
        'secondary':              '#4648d4',
        'on-secondary':           '#ffffff',
        'secondary-container':    '#6063ee',
        'on-secondary-container': '#fffbff',
        'secondary-fixed':        '#e1e0ff',
        'secondary-fixed-dim':    '#c0c1ff',
        'on-secondary-fixed':     '#07006c',
        'on-secondary-fixed-variant': '#2f2ebe',
        'tertiary':               '#003c36',
        'on-tertiary':            '#ffffff',
        'tertiary-container':     '#00554e',
        'on-tertiary-container':  '#5fcdbf',
        'tertiary-fixed':         '#89f5e7',
        'tertiary-fixed-dim':     '#6bd8cb',
        'on-tertiary-fixed':      '#00201d',
        'on-tertiary-fixed-variant': '#005049',
        'error':                  '#ba1a1a',
        'on-error':               '#ffffff',
        'error-container':        '#ffdad6',
        'on-error-container':     '#93000a',
        'background':             '#faf8ff',
        'on-background':          '#131b2e',
        'surface-variant':        '#dae2fd',
        'ice-white':              '#F8FAFC',
        'electric-indigo':        '#4F46E5',
        'success-teal':           '#14B8A6',
        'warning-amber':          '#F59E0B',
        'error-crimson':          '#E11D48',
        'slate-gray':             '#64748B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.25rem',
        md:      '0.5rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        'stack-sm':       '0.5rem',
        'stack-md':       '1rem',
        'stack-lg':       '2rem',
        'gutter':         '1.5rem',
        'margin-mobile':  '1rem',
        'margin-desktop': '2rem',
      },
      maxWidth: {
        'max-width-content': '1200px',
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
